ServerEvents.recipes(event => {

event.remove({id: 'instrumentus:wooden_paxel'})
event.remove({id: 'instrumentus:stone_paxel'})
event.remove({id: 'instrumentus:iron_paxel'})
event.remove({id: 'instrumentus:diamond_paxel'})
event.remove({id: 'instrumentus:golden_paxel'})
event.remove({id: 'instrumentus:netherite_paxel_smithing'})
event.remove({id: 'instrumentus:diamond_sickle'})

event.remove({id: 'utilitarian:utility/iron_block_from_smelting'})
event.remove({id: 'utilitarian:utility/gold_block_from_smelting'})
event.remove({id: 'utilitarian:utility/copper_block_from_smelting'})
event.remove({id: 'utilitarian:utility/iron_block_from_blasting'})
event.remove({id: 'utilitarian:utility/gold_block_from_blasting'})
event.remove({id: 'utilitarian:utility/copper_block_from_blasting'})

event.remove({id: 'productivetrees:crates/red_delicious_apple_crate'})

event.remove({ output: 'excessive_utilities:compressed_cobbled_deepslate_1' })
event.remove({ output: 'excessive_utilities:compressed_cobbled_deepslate_10' })
event.remove({ output: 'excessive_utilities:compressed_cobbled_deepslate_11' })
event.remove({ output: 'excessive_utilities:compressed_cobbled_deepslate_12' })
event.remove({ output: 'excessive_utilities:compressed_cobbled_deepslate_13' })
event.remove({ output: 'excessive_utilities:compressed_cobbled_deepslate_14' })
event.remove({ output: 'excessive_utilities:compressed_cobbled_deepslate_15' })
event.remove({ output: 'excessive_utilities:compressed_cobbled_deepslate_16' })
event.remove({ output: 'excessive_utilities:compressed_cobbled_deepslate_2' })
event.remove({ output: 'excessive_utilities:compressed_cobbled_deepslate_3' })
event.remove({ output: 'excessive_utilities:compressed_cobbled_deepslate_4' })
event.remove({ output: 'excessive_utilities:compressed_cobbled_deepslate_5' })
event.remove({ output: 'excessive_utilities:compressed_cobbled_deepslate_6' })
event.remove({ output: 'excessive_utilities:compressed_cobbled_deepslate_7' })
event.remove({ output: 'excessive_utilities:compressed_cobbled_deepslate_8' })
event.remove({ output: 'excessive_utilities:compressed_cobbled_deepslate_9' })
event.remove({ output: 'excessive_utilities:compressed_cobblestone_1' })
event.remove({ output: 'excessive_utilities:compressed_cobblestone_10' })
event.remove({ output: 'excessive_utilities:compressed_cobblestone_11' })
event.remove({ output: 'excessive_utilities:compressed_cobblestone_12' })
event.remove({ output: 'excessive_utilities:compressed_cobblestone_13' })
event.remove({ output: 'excessive_utilities:compressed_cobblestone_14' })
event.remove({ output: 'excessive_utilities:compressed_cobblestone_15' })
event.remove({ output: 'excessive_utilities:compressed_cobblestone_16' })
event.remove({ output: 'excessive_utilities:compressed_cobblestone_2' })
event.remove({ output: 'excessive_utilities:compressed_cobblestone_3' })
event.remove({ output: 'excessive_utilities:compressed_cobblestone_4' })
event.remove({ output: 'excessive_utilities:compressed_cobblestone_5' })
event.remove({ output: 'excessive_utilities:compressed_cobblestone_6' })
event.remove({ output: 'excessive_utilities:compressed_cobblestone_7' })
event.remove({ output: 'excessive_utilities:compressed_cobblestone_8' })
event.remove({ output: 'excessive_utilities:compressed_cobblestone_9' })
event.remove({ output: 'excessive_utilities:compressed_dirt_1' })
event.remove({ output: 'excessive_utilities:compressed_dirt_10' })
event.remove({ output: 'excessive_utilities:compressed_dirt_11' })
event.remove({ output: 'excessive_utilities:compressed_dirt_12' })
event.remove({ output: 'excessive_utilities:compressed_dirt_13' })
event.remove({ output: 'excessive_utilities:compressed_dirt_14' })
event.remove({ output: 'excessive_utilities:compressed_dirt_15' })
event.remove({ output: 'excessive_utilities:compressed_dirt_16' })
event.remove({ output: 'excessive_utilities:compressed_dirt_2' })
event.remove({ output: 'excessive_utilities:compressed_dirt_3' })
event.remove({ output: 'excessive_utilities:compressed_dirt_4' })
event.remove({ output: 'excessive_utilities:compressed_dirt_5' })
event.remove({ output: 'excessive_utilities:compressed_dirt_6' })
event.remove({ output: 'excessive_utilities:compressed_dirt_7' })
event.remove({ output: 'excessive_utilities:compressed_dirt_8' })
event.remove({ output: 'excessive_utilities:compressed_dirt_9' })
event.remove({ output: 'excessive_utilities:compressed_gravel_1' })
event.remove({ output: 'excessive_utilities:compressed_gravel_10' })
event.remove({ output: 'excessive_utilities:compressed_gravel_11' })
event.remove({ output: 'excessive_utilities:compressed_gravel_12' })
event.remove({ output: 'excessive_utilities:compressed_gravel_13' })
event.remove({ output: 'excessive_utilities:compressed_gravel_14' })
event.remove({ output: 'excessive_utilities:compressed_gravel_15' })
event.remove({ output: 'excessive_utilities:compressed_gravel_16' })
event.remove({ output: 'excessive_utilities:compressed_gravel_2' })
event.remove({ output: 'excessive_utilities:compressed_gravel_3' })
event.remove({ output: 'excessive_utilities:compressed_gravel_4' })
event.remove({ output: 'excessive_utilities:compressed_gravel_5' })
event.remove({ output: 'excessive_utilities:compressed_gravel_6' })
event.remove({ output: 'excessive_utilities:compressed_gravel_7' })
event.remove({ output: 'excessive_utilities:compressed_gravel_8' })
event.remove({ output: 'excessive_utilities:compressed_gravel_9' })
event.remove({ output: 'excessive_utilities:compressed_sand_1' })
event.remove({ output: 'excessive_utilities:compressed_sand_10' })
event.remove({ output: 'excessive_utilities:compressed_sand_11' })
event.remove({ output: 'excessive_utilities:compressed_sand_12' })
event.remove({ output: 'excessive_utilities:compressed_sand_13' })
event.remove({ output: 'excessive_utilities:compressed_sand_14' })
event.remove({ output: 'excessive_utilities:compressed_sand_15' })
event.remove({ output: 'excessive_utilities:compressed_sand_16' })
event.remove({ output: 'excessive_utilities:compressed_sand_2' })
event.remove({ output: 'excessive_utilities:compressed_sand_3' })
event.remove({ output: 'excessive_utilities:compressed_sand_4' })
event.remove({ output: 'excessive_utilities:compressed_sand_5' })
event.remove({ output: 'excessive_utilities:compressed_sand_6' })
event.remove({ output: 'excessive_utilities:compressed_sand_7' })
event.remove({ output: 'excessive_utilities:compressed_sand_8' })
event.remove({ output: 'excessive_utilities:compressed_sand_9' })

event.remove({id: 'torchmaster:dreadlamp'})
event.remove({id: 'torchmaster:megatorch'})
event.remove({id: 'torchmaster:feral_flare_lantern'})

event.remove({id: 'comforts:sleeping_bag_orange'})
event.remove({id: 'comforts:sleeping_bag_brown'})
event.remove({id: 'comforts:sleeping_bag_green'})
event.remove({id: 'comforts:sleeping_bag_red'})
event.remove({id: 'comforts:sleeping_bag_black'})
event.remove({id: 'comforts:sleeping_bag_yellow'})
event.remove({id: 'comforts:sleeping_bag_lime'})
event.remove({id: 'comforts:sleeping_bag_pink'})
event.remove({id: 'comforts:sleeping_bag_gray'})
event.remove({id: 'comforts:sleeping_bag_light_gray'})
event.remove({id: 'comforts:sleeping_bag_cyan'})
event.remove({id: 'comforts:sleeping_bag_purple'})
event.remove({id: 'comforts:sleeping_bag_blue'})
event.remove({id: 'comforts:sleeping_bag_magenta'})
event.remove({id: 'comforts:sleeping_bag_light_blue'})

event.remove({id: 'extrastorage:part/storagepart_256k'})
event.remove({id: 'extrastorage:part/storagepart_1024k'})
event.remove({id: 'extrastorage:part/storagepart_4096k'})
event.remove({id: 'extrastorage:part/storagepart_16384k'})

event.remove({id: 'extrastorage:disk/shaped/disk_256k'})
event.remove({id: 'extrastorage:disk/shaped/disk_1024k'})
event.remove({id: 'extrastorage:disk/shaped/disk_4096k'})
event.remove({id: 'extrastorage:disk/shaped/disk_16384k'})

event.remove({id: 'extrastorage:storage_block/block_256k'})
event.remove({id: 'extrastorage:storage_block/block_1024k'})
event.remove({id: 'extrastorage:storage_block/block_4096k'})
event.remove({id: 'extrastorage:storage_block/block_16384k'})

event.remove({id: 'extrastorage:part/storagepart_16384b_fluid'})
event.remove({id: 'extrastorage:part/storagepart_65536b_fluid'})
event.remove({id: 'extrastorage:part/storagepart_262144b_fluid'})
event.remove({id: 'extrastorage:part/storagepart_1048576b_fluid'})

event.remove({id: 'extrastorage:disk/shaped/disk_16384b_fluid'})
event.remove({id: 'extrastorage:disk/shaped/disk_65536b_fluid'})
event.remove({id: 'extrastorage:disk/shaped/disk_262144b_fluid'})
event.remove({id: 'extrastorage:disk/shaped/disk_1048576b_fluid'})

event.remove({id: 'extrastorage:storage_block/block_16384b_fluid'})
event.remove({id: 'extrastorage:storage_block/block_65536b_fluid'})
event.remove({id: 'extrastorage:storage_block/block_262144b_fluid'})
event.remove({id: 'extrastorage:storage_block/block_1048576b_fluid'})

event.remove({id: 'extrastorage:disk/shapeless/disk_256k'})
event.remove({id: 'extrastorage:disk/shapeless/disk_1024k'})
event.remove({id: 'extrastorage:disk/shapeless/disk_4096k'})
event.remove({id: 'extrastorage:disk/shapeless/disk_16384k'})

event.remove({id: 'extrastorage:disk/shapeless/disk_16384b_fluid'})
event.remove({id: 'extrastorage:disk/shapeless/disk_65536b_fluid'})
event.remove({id: 'extrastorage:disk/shapeless/disk_262144b_fluid'})
event.remove({id: 'extrastorage:disk/shapeless/disk_1048576b_fluid'})

event.remove({id: 'actuallyadditions:crafter_on_a_stick'})

event.remove({id: 'actuallyadditions:coal_to_tiny'})
event.remove({id: 'actuallyadditions:tiny_to_coal'})

event.remove({id: 'actuallyadditions:charcoal_to_tiny'})
event.remove({id: 'actuallyadditions:tiny_to_charcoal'})

event.remove({id: 'stellaris:misc/steel_sword'})
event.remove({id: 'stellaris:misc/steel_pickaxe'})
event.remove({id: 'stellaris:misc/steel_hoe'})
event.remove({id: 'stellaris:misc/steel_shovel'})
event.remove({id: 'stellaris:misc/steel_axe'})

event.remove({id: 'pickletweaks:diamond_scythe'})

event.remove({id: 'pickletweaks:wooden_paxel'})
event.remove({id: 'pickletweaks:stone_paxel'})
event.remove({id: 'pickletweaks:iron_paxel'})
event.remove({id: 'pickletweaks:golden_paxel'})
event.remove({id: 'pickletweaks:diamond_paxel'})
event.remove({id: 'pickletweaks:netherite_paxel'})

event.remove({id: 'pickletweaks:wooden_sickle'})
event.remove({id: 'pickletweaks:stone_sickle'})
event.remove({id: 'pickletweaks:iron_sickle'})
event.remove({id: 'pickletweaks:golden_sickle'})
event.remove({id: 'pickletweaks:diamond_sickle'})
event.remove({id: 'pickletweaks:netherite_sickle'})

event.remove({id: 'pickletweaks:watering_can'})

event.remove({id: 'croptopia:popcorn_from_corn'})
event.remove({id: 'croptopia:popcorn_from_smoking_corn'})
event.remove({id: 'croptopia:campfire_popcorn'})

event.remove({id: 'synergy:rustic_metal_blasting'})

event.remove({id: 'enderio:powdered_coal'})

event.remove({id: 'slabmachines:slab_from_crafting_table'})

event.remove({id: 'silentgear:iron_rod'})

event.remove({id: 'silentgems:silver_ingot_from_block'})

event.remove({id: 'glassential:glass_slab'})

event.remove({id: 'minecraft:stick_from_bamboo_item'})

event.remove({id: 'oritech:crafting/alloy/steel'})
event.remove({id: 'oritech:crafting/alloy/electrum'})

event.remove({id: 'occultism:crushing/coal_dust_from_tag'})

event.remove({id: 'occultism:crushing/ender_pearl_dust_from_tag'})

event.remove({id: 'extrastorage:advanced_importer'})
event.remove({id: 'extrastorage:advanced_exporter'})

event.remove({id: 'supplementaries:stone_tile'})

event.remove({id: 'malum:coal_fragment'})
event.remove({id: 'malum:charcoal_fragment'})

event.remove({id: 'dynamiducts:bronze_ingot_from_copper'})
event.remove({id: 'dynamiducts:electrum_ingot_from_gold'})
event.remove({id: 'dynamiducts:electrum_ingot_from_nuggets'})
event.remove({id: 'dynamiducts:electrum_nugget_from_ingot'})
event.remove({id: 'dynamiducts:invar_ingot_from_iron'})
event.remove({id: 'dynamiducts:lead_ingot_from_iron'})
event.remove({id: 'dynamiducts:lead_ingot_from_nuggets'})
event.remove({id: 'dynamiducts:lead_nugget_from_ingot'})
event.remove({id: 'dynamiducts:silver_ingot_from_iron'})
event.remove({id: 'dynamiducts:silver_ingot_from_nuggets'})
event.remove({id: 'dynamiducts:silver_nugget_from_ingot'})
event.remove({id: 'dynamiducts:tin_ingot_from_iron'})
event.remove({id: 'dynamiducts:tin_ingot_from_nuggets'})
event.remove({id: 'dynamiducts:tin_nugget_from_ingot'})

event.remove({id: 'mysticalagriculture:essence/common/niter'})
event.remove({id: 'mysticalagriculture:seed/infusion/copper_alloy'})

event.remove({id: 'dndesires:crafting/coal_from_coal_piece'})
event.remove({id: 'dndesires:crafting/coal_piece_from_coal'})

event.remove({id: 'voidtotem:crafting_recipe'})

event.remove({id: 'rspolymorph:test_stick_1'})
event.remove({id: 'rspolymorph:test_stick_2'})

event.remove({id: 'dndesires:crafting/diamond_shard_from_diamond'})
event.remove({id: 'dndesires:crafting/diamond_from_diamond_shard'})

event.remove({id: 'dndesires:crafting/lapis_lazuli_shard_from_lapis_lazuli'})

event.remove({id: 'extradelight:cutting/cutting/cut_apples'})
event.remove({id: 'extradelight:cutting/cutting/sliced_tomato'})
event.remove({id: 'extradelight:cutting/cutting/sliced_onion'})
event.remove({id: 'extradelight:cutting/cutting/sliced_beetroot_knife'})
event.remove({id: 'extradelight:cutting/cutting/bread_knife'})

event.remove({id: 'quark:world/crafting/woodsets/azalea/azalea_chest_wood'})
event.remove({id: 'quark:world/crafting/woodsets/azalea/azalea_chest'})
event.remove({id: 'quark:building/chests/birch_chest_wood'})
event.remove({id: 'quark:building/crafting/chests/birch_chest'})
event.remove({id: 'quark:building/chests/cherry_chest_wood'})
event.remove({id: 'quark:building/crafting/chests/cherry_chest'})
event.remove({id: 'quark:building/chests/oak_chest_wood'})
event.remove({id: 'quark:building/crafting/chests/oak_chest'})
event.remove({id: 'quark:world/crafting/woodsets/ancient/ancient_chest_wood'})
event.remove({id: 'quark:world/crafting/woodsets/ancient/ancient_chest'})
event.remove({id: 'quark:building/chests/acacia_chest_wood'})
event.remove({id: 'quark:building/crafting/chests/acacia_chest'})
event.remove({id: 'quark:world/crafting/woodsets/blossom/blossom_chest_wood'})
event.remove({id: 'quark:world/crafting/woodsets/blossom/blossom_chest'})
event.remove({id: 'quark:building/chests/spruce_chest_wood'})
event.remove({id: 'quark:building/crafting/chests/spruce_chest'})
event.remove({id: 'quark:building/chests/bamboo_chest_wood'})
event.remove({id: 'quark:building/crafting/chests/bamboo_chest'})
event.remove({id: 'quark:building/chests/crimson_chest_wood'})
event.remove({id: 'quark:building/crafting/chests/crimson_chest'})
event.remove({id: 'quark:building/chests/jungle_chest_wood'})
event.remove({id: 'quark:building/crafting/chests/jungle_chest'})
event.remove({id: 'quark:building/chests/dark_oak_chest_wood'})
event.remove({id: 'quark:building/crafting/chests/dark_oak_chest'})
event.remove({id: 'quark:building/chests/mangrove_chest_wood'})
event.remove({id: 'quark:building/crafting/chests/mangrove_chest'})
event.remove({id: 'quark:building/chests/warped_chest_wood'})
event.remove({id: 'quark:building/crafting/chests/warped_chest'})

event.remove({id: 'ascended_quark:yagroot_chest'})
event.remove({id: 'ascended_quark:sunroot_chest'})
event.remove({id: 'ascended_quark:roseroot_chest'})
event.remove({id: 'ascended_quark:cruderoot_chest'})
event.remove({id: 'ascended_quark:conberry_chest'})
event.remove({id: 'ascended_quark:skyroot_chest'})

event.remove({id: 'ascended_quark:holystone_furnace'})
event.remove({id: 'quark:building/crafting/furnaces/blackstone_furnace'})
event.remove({id: 'quark:building/crafting/furnaces/deepslate_furnace'})

event.remove({id: 'excessive_utilities:last_millennium_portal'})
event.remove({id: 'excessive_utilities:depths_portal'})
event.remove({id: 'excessive_utilities:magnum_torch'})

event.remove({id: 'quark:building/crafting/compressed/vanilla_nether_wart_block_4x4'})

event.remove({id: 'utilitarian:utility/nether_wart'})

event.remove({id: 'excessive_utilities:angel_block'})
event.remove({id: 'excessive_utilities:angel_ring_conversion_invisible'})
event.remove({id: 'excessive_utilities:unstable/angel_ring_invisible'})
event.remove({id: 'excessive_utilities:unstable/angel_ring_feather'})
event.remove({id: 'excessive_utilities:unstable/angel_ring_butterfly'})
event.remove({id: 'excessive_utilities:unstable/angel_ring_demon'})
event.remove({id: 'excessive_utilities:unstable/angel_ring_gold'})
event.remove({id: 'excessive_utilities:angel_ring_conversion_feather'})
event.remove({id: 'excessive_utilities:angel_ring_conversion_butterfly'})
event.remove({id: 'excessive_utilities:angel_ring_conversion_demon'})
event.remove({id: 'excessive_utilities:angel_ring_conversion_gold'})
event.remove({id: 'excessive_utilities:angel_ring_conversion_bat'})
event.remove({id: 'excessive_utilities:unstable/angel_ring_bat'})

event.remove({id: 'modular_angelring:gold_ring'})

// Recipes below were accidentally left enabled in the mod even though compat is not present.
event.remove({id: 'ironfurnaces:upgrades/upgrade_allthemodium'})
event.remove({id: 'ironfurnaces:upgrades/upgrade_unobtainium'})
event.remove({id: 'ironfurnaces:upgrades/upgrade_vibranium'})

// Mod below is disabled in favor of BetterBlockZ mod.
event.remove({mod: 'xtonesreworked'})

// (Prefab) : Removed whole mod (remove line at the bottom to re-enable recipes.)
// Recipes will not show in EMI due to being hidden, go into: 'Limitless-8\kubejs\server_scripts\hidden_itemstacks.js'
// Remove all entries in it with 'prefab' as the mod id. Save file.
// You also need to "regen" the prefab config, go into 'config' folder and remove the 'Prefab.json' file, then restart game.
event.remove({mod: 'prefab'})

});